version: '3'
services:
  minio-server:
    image: minio/minio:RELEASE.2021-07-30T00-02-00Z.fips
    container_name: 'minio'
    ports:
      - 9000:9000
      - 9001:9001
    env_file: .env
    entrypoint: sh
    command: -c "
      /usr/bin/minio server /data --console-address ':9001';
      "
    volumes:
      - minio-data:/data

  create-bucket:
    image: minio/mc:RELEASE.2021-07-27T06-46-19Z
    container_name: 'minio-client'
    depends_on: 
      - minio-server
    env_file: .env
    entrypoint: sh
    command: -c '
      mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD --api S3v4;
      [ `mc ls myminio | wc -l` == 0 ] && mc mb myminio/$$BUCKET_NAME;
      sed -e "s/%%BUCKET_NAME%%/$$BUCKET_NAME/g" /tmp/public-access-policy.json > /tmp/policy.json;
      mc policy set-json /tmp/policy.json myminio/$$BUCKET_NAME;
      '
    volumes:
      - ./public-access-policy.json:/tmp/public-access-policy.json
    profiles:
      - tools

volumes:
  minio-data:
